### ISSUE TITLE
Remember user selections

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/hexbotMQTTScriptCompiler-#16]
Save user choices to a file and auto-populate the default values each time from that file. This will make testing less tedious.

**Comment by nerdoug** [comment]
Pondering a simplified symbol substitution scheme that could include default values for each of the interactive prompts when you do a compile. One of these might be a environment symbol that specifies the MQTT script file directory where the compiled output should be placed ( after the "01__hb-" filename prefic, and .js file extension are added.)

**Comment by theAgingApprentice** [comment]
The symbol file may make this obsolete. Could add feature to save user chooses and then pull them up as defaults next time.

**Comment by nerdoug** [comment]
completed in git merge 29
