### ISSUE TITLE
Write MQTTfx file out to the MQTTfx script directory

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/hexbotMQTTScriptCompiler-#24]
Put this parameter in the symbol file and have the output from the fxFile object go right to the directory where MQTTfx looks for scripts. This will make our workflow more efficient.

**Comment by nerdoug** [comment]
This is done if you use the symbol $O to describe your output filename, and its path, relative or absolute.

In my symbol file I point to the appropriate MQTT folder in the Windows environment with an absolute path:

> / output file location, including absolute path
> O C:\Users\DougElliott\AppData\Local\MQTT-FX\scripts\01__hb-test-from-folder.js

The input file in $I uses a relative path:

> / input file location, including relative path
> I scripts\test-from-folder.txt

**Comment by nerdoug** [comment]
completed in git merge 29
