### ISSUE TITLE
Put input script and template files into a sub directory

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/hexbotMQTTScriptCompiler-#25]
Place all the input files into a sub-directory to keep things tidy.

**Comment by nerdoug** [comment]
If you use the $I symbol in symbols.txt to define what the input file name is, you can include whatever path you like.
I've created a scripts folder, and my symbol file defines I as:

> / input file location, including relative path
> I scripts\test-from-folder.txt

I've left the template file in the main folder for now.

The same technique lets you put the compiled .js file directly into the folder that MQTT.fx looks at:

> / output file location, including absolute path
> O C:\Users\DougElliott\AppData\Local\MQTT-FX\scripts\01__hb-test-from-folder.js

**Comment by nerdoug** [comment]
completed in git merge 29
