### ISSUE TITLE
Create new object for the symbol file

### ISSUE THREAD

**Issue by theAgingApprentice** [theAgingApprentice/hexbotMQTTScriptCompiler-#26]
Create a separate object for the symbol file and pass a reference to it to the fxFile class.

**Comment by nerdoug** [comment]
I went at this differently. I duplicated the  small piece of code that builds the symbol arrays from the symbols.txt file in both the template and script classes, and the 2 related routines. This gets rid of the need for calling methods in other objects. The MQTT object also needed do do a symbol lookup for the output filename, but main is able to call the appropriate method in one of the other objects, and pass the filename in the call to MQTT.create. It's all working, and handles the cases shown in this test symbol file:

> / test symbol template (next line is blank)
> 
> / comment with continuation starting with a space character
>  so I can drone on
>  in extended comments
> 
> /and now we actually define some symbols: 
> / H is the name of the robot, for MQTT purposes
>  Andrew: Hexbot94B97E5F4A40
>  Doug:   Hexbot3C61054ADD98
> H Hexbot3C61054ADD98
> 
> / input file location, including relative path
> I scripts\test-from-folder.txt
> 
> / output file location, including absolute path
> O C:\Users\DougElliott\AppData\Local\MQTT-FX\scripts\01__hb-test-from-folder.js
> 
> / parameterized leg number that will be tested by resulting js code
> L 5
> 
> / number of test cycles to repeat (plus the initial one)
> C 4
> 
> / time interval in milliseconds for each leg movement
> T 600
> 

Here's the associated script file test-from-folder.txt (which is in the new scripts folder)

> symdef BotID Hexbot3C61054ADD98
> MoveToHomePosition
> CycleStart 1
> MoveRelLastLocal $L, 0, 4, 0,
> Doit $T
> MoveRelLastLocal $l, 4, 0, 0,
> Doit $T
> MoveRelLastLocal $L, 0, 0, -4,
> Doit $T
> MoveRelLastLocal $L, 0, 0, 4,
> Doit $T
> MoveRelHomeLocal $L, -4, 0, 0,
> Doit $T
> MoveRelHomeLocal $L, 0, -4, 0,
> Doit $T
> CycleEnd 1
> ExecuteCycle 1,$C
>

**Comment by nerdoug** [comment]
completed in git merge 29
